// wordData.js
export const wordBanks = {
  2: [
    { hebrew: 'אב', transliteration: 'av', meaning: 'father' },
    { hebrew: 'אם', transliteration: 'em', meaning: 'mother' },
    { hebrew: 'בא', transliteration: 'ba', meaning: 'comes' },
    { hebrew: 'גן', transliteration: 'gan', meaning: 'garden' },
    { hebrew: 'דג', transliteration: 'dag', meaning: 'fish' },
    { hebrew: 'רע', transliteration: 'ra', meaning: 'bad' },
    { hebrew: 'חג', transliteration: 'chag', meaning: 'holiday' },
    { hebrew: 'שם', transliteration: 'shem', meaning: 'name' },
    { hebrew: 'עץ', transliteration: 'etz', meaning: 'tree' },
    { hebrew: 'אש', transliteration: 'esh', meaning: 'fire' },
    { hebrew: 'אי', transliteration: 'ee', meaning: 'island' },
    { hebrew: 'עד', transliteration: 'ad', meaning: 'forever/eternity' },
    { hebrew: 'או', transliteration: 'o', meaning: 'or' },
    { hebrew: 'זה', transliteration: 'ze', meaning: 'this' },
    { hebrew: 'של', transliteration: 'shel', meaning: 'of' },
    { hebrew: 'גם', transliteration: 'gam', meaning: 'also' },
  ],
  3: [
    { hebrew: 'יום', transliteration: 'yom', meaning: 'day' },
    { hebrew: 'מים', transliteration: 'mayim', meaning: 'water' },
    { hebrew: 'ילד', transliteration: 'yeled', meaning: 'boy' },
    { hebrew: 'אור', transliteration: 'or', meaning: 'light' },
    { hebrew: 'המן', transliteration: 'haman', meaning: 'Haman' },
    { hebrew: 'רעש', transliteration: 'ra\'ash', meaning: 'noise' },
    { hebrew: 'מלך', transliteration: 'melech', meaning: 'king' },
    { hebrew: 'נס', transliteration: 'nes', meaning: 'miracle' },
    { hebrew: 'אזן', transliteration: 'ozen', meaning: 'ear' },
    { hebrew: 'שמח', transliteration: 'sameach', meaning: 'happy' },
    { hebrew: 'גדל', transliteration: 'gadal', meaning: 'grew' },
    { hebrew: 'למה', transliteration: 'lamah', meaning: 'why' },
    { hebrew: 'חול', transliteration: 'chol', meaning: 'sand' },
    { hebrew: 'אכל', transliteration: 'achal', meaning: 'he ate' },
    { hebrew: 'חום', transliteration: 'chum', meaning: 'brown' },
    { hebrew: 'כלב', transliteration: 'kelev', meaning: 'dog' },
    { hebrew: 'עלה', transliteration: 'aleh', meaning: 'leaf' },
    { hebrew: 'עוף', transliteration: 'ouf', meaning: 'bird/fowl' },
    { hebrew: 'דבש', transliteration: 'dvash', meaning: 'honey' },
    { hebrew: 'בגד', transliteration: 'beged', meaning: 'garment' },
  ],
  4: [
    { hebrew: 'שלום', transliteration: 'shalom', meaning: 'peace' },
    { hebrew: 'תודה', transliteration: 'toda', meaning: 'thank you' },
    { hebrew: 'ילדה', transliteration: 'yalda', meaning: 'girl' },
    { hebrew: 'אסתר', transliteration: 'esther', meaning: 'Esther' },
    { hebrew: 'משתה', transliteration: 'mishteh', meaning: 'feast' },
    { hebrew: 'אדר', transliteration: 'adar', meaning: 'Adar' },
    { hebrew: 'רעשן', transliteration: 'ra\'ashan', meaning: 'noisemaker' },
    { hebrew: 'שושן', transliteration: 'shushan', meaning: 'Shushan' },
    { hebrew: 'חתול', transliteration: 'chatul', meaning: 'cat' },
    { hebrew: 'בקשה', transliteration: 'bakasha', meaning: 'request' },
    { hebrew: 'כביש', transliteration: 'kvish', meaning: 'road' },
    { hebrew: 'מטבח', transliteration: 'mitbach', meaning: 'kitchen' },
    { hebrew: 'שמים', transliteration: 'shamayim', meaning: 'sky/heavens' },
    { hebrew: 'תפוח', transliteration: 'tapuach', meaning: 'apple' },
    { hebrew: 'ברוך', transliteration: 'baruch', meaning: 'blessed' },
    { hebrew: 'ארון', transliteration: 'aron', meaning: 'closet/ark' },
    { hebrew: 'גלות', transliteration: 'galut', meaning: 'exile' },
  ],
  5: [
    { hebrew: 'מרדכי', transliteration: 'mordechai', meaning: 'Mordechai' },
    { hebrew: 'פורים', transliteration: 'purim', meaning: 'Purim holiday' },
    { hebrew: 'מגילה', transliteration: 'megila', meaning: 'scroll' },
    { hebrew: 'תרגום', transliteration: 'targum', meaning: 'translation' },
    { hebrew: 'תינוק', transliteration: 'tinok', meaning: 'baby' },
    { hebrew: 'בריאה', transliteration: 'briyah', meaning: 'creation' },
    { hebrew: 'מלאכה', transliteration: 'melacha', meaning: 'work' },
    { hebrew: 'פרחים', transliteration: 'prachim', meaning: 'flowers' },
    { hebrew: 'צעצוע', transliteration: 'tsa\'tsu\'a', meaning: 'toy' },
    { hebrew: 'חולצה', transliteration: 'chultza', meaning: 'shirt' },
    { hebrew: 'בננות', transliteration: 'bananot', meaning: 'bananas' },
    { hebrew: 'נמרים', transliteration: 'nemarim', meaning: 'tigers' },
    { hebrew: 'ספינה', transliteration: 'sfina', meaning: 'ship' },
   ],
  6: [
    { hebrew: 'תחפושת', transliteration: 'tachposet', meaning: 'costume' },
    { hebrew: 'אומנות', transliteration: 'omanut', meaning: 'art' },
    { hebrew: 'מוזיקה', transliteration: 'muzika', meaning: 'music' },
    { hebrew: 'מחשבות', transliteration: 'machshavot', meaning: 'thoughts' },
    { hebrew: 'מדרגות', transliteration: 'madregot', meaning: 'stairs' },
    { hebrew: 'תפוחים', transliteration: 'tapuchim', meaning: 'apples' },
    { hebrew: 'גלידות', transliteration: 'glidot', meaning: 'ice creams' },
    { hebrew: 'כתובות', transliteration: 'ktuvot', meaning: 'addresses' },
    { hebrew: 'פרסומת', transliteration: 'pirsomet', meaning: 'advertisement' },
    { hebrew: 'שולחנות', transliteration: 'shulchanot', meaning: 'tables' },
    { hebrew: 'פגישות', transliteration: 'pgishot', meaning: 'meetings' },
    { hebrew: 'צעצועים', transliteration: 'tsatzu\'im', meaning: 'toys' },
    { hebrew: 'משקפיים', transliteration: 'mishkafayim', meaning: 'glasses' },
  ],
  // 7-letter words (with space)
  7: [
    { hebrew: 'חג שמח', transliteration: 'chag sameach', meaning: 'happy holiday' },
    { hebrew: 'כל טוב', transliteration: 'kol tuv', meaning: 'all the best' },
    { hebrew: 'שבת שלום', transliteration: 'shabbat shalom', meaning: 'peaceful sabbath' },
    { hebrew: 'בית ספר', transliteration: 'beit sefer', meaning: 'school (house of book)' },
    { hebrew: 'יום טוב', transliteration: 'yom tov', meaning: 'good day/holiday' },
    { phrase: 'לילה טוב', transliteration: 'laila tov', meaning: 'good night' },
    { phrase: 'מים קרים', transliteration: 'mayim karim', meaning: 'cold water' },
    { phrase: 'מים חמים', transliteration: 'mayim chamim', meaning: 'warm water' },
    { phrase: 'אש בוערת', transliteration: 'esh bo\'eret', meaning: 'burning fire' },
    { phrase: 'ים סוער', transliteration: 'yam so\'er', meaning: 'stormy sea' }
  ],
  // 8-letter words (with space)
  8: [
    { hebrew: 'מזל טוב', transliteration: 'mazal tov', meaning: 'good luck/congratulations' },
    { hebrew: 'ראש השנה', transliteration: 'rosh hashanah', meaning: 'new year' },
    { hebrew: 'ערב טוב', transliteration: 'erev tov', meaning: 'good evening' },
    { hebrew: 'בוקר טוב', transliteration: 'boker tov', meaning: 'good morning' },
    { hebrew: 'תודה רבה', transliteration: 'todah rabah', meaning: 'thank you very much' },
    { phrase: 'יום הולדת', transliteration: 'yom huledet', meaning: 'birthday' },
    { phrase: 'עולם חדש', transliteration: 'olam chadash', meaning: 'new world' },
    { phrase: 'חיים יפים', transliteration: 'chayim yafim', meaning: 'beautiful life' },
    { phrase: 'עיר גדולה', transliteration: 'ir gdola', meaning: 'big city' },
    { phrase: 'עין כחולה', transliteration: 'ayin kchula', meaning: 'blue eye' }
   ],
  // 9-letter words (with space)
  9: [
    { hebrew: 'שנה טובה', transliteration: 'shanah tovah', meaning: 'good year' },
    { hebrew: 'לילה טוב', transliteration: 'lailah tov', meaning: 'good night' },
    { hebrew: 'שלום עליכם', transliteration: 'shalom aleichem', meaning: 'peace be upon you' },
    { hebrew: 'מה שלומך', transliteration: 'ma shlomcha', meaning: 'how are you' },
    { hebrew: 'פורים שמח', transliteration: 'purim sameach', meaning: 'happy purim' },
    { phrase: 'חגים שמחים', transliteration: 'chagim sameach', meaning: 'happy holidays' },
    { phrase: 'מים מתוקים', transliteration: 'mayim metukim', meaning: 'sweet water' },
    { phrase: 'פנים שמחים', transliteration: 'panim sameachim', meaning: 'cheerful face' },
    { phrase: 'חיים מלאים', transliteration: 'chayim meleim', meaning: 'full life' },
    { phrase: 'ידיים חזקות', transliteration: 'yadaim chazakot', meaning: 'strong hands' }
  ]
};
